from LongNet.iterations.DilatedAttentionOld import DilatedAttentionold
from LongNet.iterations.DilatedAttentionOP import DilatedAttentionOP
from LongNet.iterations.DynamicDilatedAttention import DynamicDilatedAttention
