from longnet.iterations.DilatedAttentionOld import DilatedAttentionold
from longnet.iterations.DilatedAttentionOP import DilatedAttentionOP
from longnet.iterations.DynamicDilatedAttention import DynamicDilatedAttention